services:
    this:
      deploy:
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          tcpSocket:
            port: ${this.ingress.http-api.port}
          timeoutSeconds: 1
        resources:
          minimal: 
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 200Mi
          normal: 
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 4
              memory: 512Mi
      ingress:
        http-api:
          port: 3000
          controllers:
            router:
            - path: /
              host: ${project.endpoints.site}
              options:
                ssl_verify_client: ${project.router.mutual-tls.enabled}